//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthyFood.SQL
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CHITIETDONTHANG = new HashSet<CHITIETDONTHANG>();
        }
    
        public int MaSanPham { get; set; }
        public string TenSanPham { get; set; }
        public Nullable<decimal> Giaban { get; set; }
        public string Mota { get; set; }
        public string Anhbia { get; set; }
        public Nullable<System.DateTime> Ngaycapnhat { get; set; }
        public Nullable<int> Soluongton { get; set; }
        public Nullable<int> MaCD { get; set; }
        public Nullable<int> MaNCC { get; set; }
        public Nullable<bool> DaXoa { get; set; }
        public Nullable<bool> DacTrung { get; set; }
        public Nullable<int> Review { get; set; }
        public string TinhTrang { get; set; }
        public string GiaoHang { get; set; }
        public string TrongLuong { get; set; }
        public HttpPostedFileBase uploadImage { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDONTHANG> CHITIETDONTHANG { get; set; }
        public virtual CHUDE CHUDE { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
    }
}
